name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the
        existing and past issues](https://github.com/pytorch/torchdynamo/issues)
  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error logs
      description: |
        Please provide the error you're seeing
      placeholder: |
        Error...
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Minified repro
      description: |
        Please run the minifier on your example and paste the minified code below 
        Learn more here https://github.com/pytorch/torchdynamo/blob/main/documentation/TROUBLESHOOTING.md
      placeholder: |
        env TORCHDYNAMO_REPRO_AFTER="aot" python your_model.py
        or
        env TORCHDYNAMO_REPRO_AFTER="dynamo" python your_model.py

        import torch
        ... 

        # torch version: 1.13.....

        class Repro(torch.nn.Module)
    validations:
      required: true
  
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: | 
        Which component is not working for you?
        Try the below in order
        If dynamo.optimize("eager") fails then select dynamo 
        If dynamo.optimize("aot_eager") fails then select aot_eager
        If dynamo.optimize("inductor") fails then select inductor
      options:
        - Dynamo
        - AOT 
        - Inductor
    validations:
      required: true